# Generated by Django 3.0.1 on 2020-07-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='media\\articles\\images'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(default='media\\tags\\images\\black.jpg', null=True, upload_to='media\\tags\\images'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='image',
            field=models.ImageField(default='media\\writers\\images\\default.jpg', null=True, upload_to='media\\writers\\images'),
        ),
    ]
