# Generated by Django 3.0.1 on 2020-06-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_writer_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='bio',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
