# Generated by Django 3.0.1 on 2020-07-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200702_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(default='media/tags/images/Metallica_-_Metallica_cover.jpg', upload_to='media/tags/images'),
        ),
    ]
