# Generated by Django 3.0.1 on 2020-07-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(default='tags/images/Metallica_-_Metallica_cover.jpg', upload_to='tags/images'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='image',
            field=models.ImageField(default='writers/images/default.jpg', upload_to='writers/images'),
        ),
    ]
