# Generated by Django 3.0.1 on 2020-06-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_edited',
            field=models.DateTimeField(),
        ),
    ]
