# Generated by Django 3.0.1 on 2020-06-08 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200608_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='last_edited',
        ),
    ]
