# Generated by Django 3.0.1 on 2020-07-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200703_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(default='media/tags/images/Metallica_-_Metallica_cover.jpg', upload_to='tags/images'),
        ),
    ]
