# Generated by Django 3.0.1 on 2020-06-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_last_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='last_edit',
        ),
    ]
