# Generated by Django 3.0.1 on 2020-07-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200704_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='image',
            field=models.ImageField(default='media/writers/images/default.jpg', upload_to='media/writers/images'),
        ),
    ]
