# Generated by Django 3.0.1 on 2020-06-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_last_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
