# Generated by Django 3.0.1 on 2020-06-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_writer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='photo',
            field=models.ImageField(default='wormhole-ft.jpg', upload_to=''),
        ),
    ]
