# Generated by Django 3.0.1 on 2020-06-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200609_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
