# Generated by Django 3.0.1 on 2020-06-11 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200609_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='photo',
            new_name='image',
        ),
    ]
