# Generated by Django 3.0.1 on 2020-06-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='media/articles/images'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='image',
            field=models.ImageField(default='media/writers/images/default.jpg', upload_to='media/writers/images'),
        ),
    ]
