# Generated by Django 3.0.1 on 2020-06-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200624_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
