# Generated by Django 3.0.1 on 2020-06-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_writer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='age',
            field=models.IntegerField(default=-1),
        ),
    ]
